# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dmis_countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Continent_GEO', models.CharField(max_length=255)),
                ('Continent_ID', models.IntegerField()),
                ('CountryID', models.IntegerField()),
                ('RegionID', models.IntegerField()),
                ('IFID', models.IntegerField()),
                ('FIPS_Cntry', models.CharField(max_length=255)),
                ('GMI_CNTRY', models.CharField(max_length=255)),
                ('CountryName', models.CharField(max_length=255)),
                ('ISO', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Dmis_disasters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DisasterTypeName', models.CharField(max_length=255)),
                ('DisasterTypeNameFR', models.CharField(max_length=255)),
                ('DisasterTypeNameES', models.CharField(max_length=255)),
                ('aggregation', models.CharField(max_length=255)),
                ('DisasterTypeID', models.IntegerField()),
            ],
        ),
    ]
