# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20161123_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dmis_numericalreport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumericDetailsID', models.IntegerField()),
                ('ReportID', models.IntegerField()),
                ('NumberOfInjured', models.IntegerField()),
                ('NumberOfCasualties', models.IntegerField()),
                ('NumberOfMissing', models.IntegerField()),
                ('NumberOfAffected', models.IntegerField()),
                ('NumberOfLocalStaffInvolved', models.IntegerField()),
                ('NumberOfVolunteersInvolved', models.IntegerField()),
                ('NumberOfDisplaced', models.IntegerField()),
                ('NumberOfAssistedByRC', models.IntegerField()),
                ('NumberOfExpatsDelegates', models.IntegerField()),
            ],
        ),
    ]
