# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_dmis_numericalreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmis_field_report',
            name='NumericalReport',
            field=models.ManyToManyField(to='main.Dmis_numericalreport'),
        ),
    ]
