# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 19:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_dmis_field_report_numericalreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dmis_disasters',
            name='aggregation',
        ),
    ]
