# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20161123_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmis_field_report',
            name='ActionTakenID',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dmis_field_report',
            name='BriefSummary',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='dmis_field_report',
            name='Country',
            field=models.ManyToManyField(blank=True, to='main.Dmis_countries'),
        ),
        migrations.AlterField(
            model_name='dmis_field_report',
            name='DisasterType',
            field=models.ManyToManyField(blank=True, to='main.Dmis_disasters'),
        ),
        migrations.AlterField(
            model_name='dmis_field_report',
            name='ReportGUID',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dmis_field_report',
            name='Summary',
            field=models.CharField(max_length=5000),
        ),
    ]
