# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20161123_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmis_field_report',
            name='BriefSummary',
            field=models.CharField(max_length=2500),
        ),
    ]
