# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20161123_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmis_field_report',
            name='ActionTaken',
            field=models.CharField(max_length=2500),
        ),
    ]
