# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20161123_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmis_field_report',
            name='ActionTakenByFederation',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dmis_field_report',
            name='ActionTakenByOthers',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dmis_field_report',
            name='ActionTakenByPns',
            field=models.TextField(),
        ),
    ]
