# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 19:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_dmis_reponse_tools'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dmis_reponse_tools',
            new_name='Dmis_response_tools',
        ),
    ]
