# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20161128_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmis_field_report',
            name='ResponseTools',
            field=models.ManyToManyField(blank=True, to='main.Dmis_response_tools'),
        ),
    ]
